#!/bin/sh

CGMINER_BIN=`which cgminer`
BFGMINER_BIN=`which bfgminer`
CONFIG_FILE=/usr/local/bin/.miner_opts.sh

whiptail --msgbox "Welcome to the RPi controller for Zeus/GAW ASIC miners! The following menus will walk you through getting your miners up and running quickly." 12 75 1
whiptail --msgbox "Note that the configuration dialog accepts arguments as they are provided and peforms only minimal input validation.\n\nAfter the configuration has completed and your RPi reboots, ensure that the miner is running correctly using 'screen -r'" 14 75 1

MINER=$(whiptail --radiolist "Select mining package to use" 18 75 10 --title "Miner Configuration" "cg" "cgminer 4.3.5         " ON "bfg" "bfgminer 4.6.0        " OFF 3>&1 1>&2 2>&3)
        if [ $? -eq 0 ]; then
                case "$MINER" in
                        "cg")
                                ;;
                        "bfg")
                                ;;
                        *)
                                whiptail --msgbox "Invalid option" 12 50 2
                                return 1
                                ;;
                        esac
                else
                        exit
        fi

ASIC_TYPE=$(whiptail --radiolist "Select ASIC miner" 18 75 10 --title "Miner Configuration" \
        "blizzard"      "Zeus Blizzard / GAW Fury             " ON \
        "blackwidow"    "Black Widow                          " OFF \
        "falcon"        "Falcon                               " OFF \
        "warmachine"    "War Machine                          " OFF \
        3>&1 1>&2 2>&3)
        if [ $? -eq 0 ]; then
                case "$ASIC_TYPE" in
                "blizzard")
                        ASIC_CHIPS=6
                        ASIC_CLOCK_TMP=328
                        ;;
                "blackwidow")
                        ASIC_CHIPS=64
                        ASIC_CLOCK_TMP=300
                        ;;
                "falcon")
                        ASIC_CHIPS=128
                        ASIC_CLOCK_TMP=328
                        ;;
                "warmachine")
                        ASIC_CHIPS=256
                        ASIC_CLOCK_TMP=328
                        ;;
                *)
                        whiptail --msgbox "Invalid option" 12 50 2
                        return 1
                        ;;
                esac
        else
                exit
        fi

        #while [ ! "$?" ]; do
        while true; do
                ASIC_CLOCK=$(whiptail --inputbox "Enter clock speed in Mhz; usually 328 Mhz but can be clocked higher (at your own risk) or lower (for greater efficiency & stability). Confirm the correct clock settings for your device." 10 75 ${ASIC_CLOCK_TMP} --title "Clock Speed" 3>&1 1>&2 2>&3)
                if [ $? -eq 1 ]; then
                        exit
                else
                        if [ ! -z $ASIC_CLOCK ] && [ $ASIC_CLOCK -eq $ASIC_CLOCK 2> /dev/null ]; then
                                if [ $ASIC_CLOCK -ge "100" ] && [ $ASIC_CLOCK -le "350" ]; then
                                        break
                                fi
                        fi
                fi
        done

        while [ ! "${SERVER}" ]; do
                SERVER=$(whiptail --inputbox "Enter mining host and port\n(example: stratum+tcp://pool.example.com:3333)" 8 75 "stratum+tcp://" --title "Miner Configuration" 3>&1 1>&2 2>&3)
                if [ $? -eq 1 ]; then
                        exit
                fi
        done

        while [ ! "${MINER_USER}" ]; do
                MINER_USER=$(whiptail --inputbox "Enter username" 8 75 --title "Miner Configuration" 3>&1 1>&2 2>&3)
                if [ $? -eq 1 ]; then
                        exit
                fi
        done

        while [ ! "${MINER_PASS}" ]; do
                MINER_PASS=$(whiptail --inputbox "Enter password" 8 75 --title "Miner Configuration" 3>&1 1>&2 2>&3)
                if [ $? -eq 1 ]; then
                        exit
                fi
        done

case "$MINER" in
"cg")
        CONF="${CGMINER_BIN} --scrypt --scan-serial zeus:auto --zeus-clock ${ASIC_CLOCK} --zeus-chips ${ASIC_CHIPS} -o ${SERVER} -u ${MINER_USER} -p ${MINER_PASS}"
        echo ${CONF} > ${CONFIG_FILE}
        chmod +x ${CONFIG_FILE}
        ;;
"bfg")
        CONF="${BFGMINER_BIN} --scrypt -S zeusminer:all --set zeusminer:clock=${ASIC_CLOCK} --set zeusminer:chips=${ASIC_CHIPS} -o ${SERVER} -u ${MINER_USER} -p ${MINER_PASS}"
        echo ${CONF} > ${CONFIG_FILE}
        chmod +x ${CONFIG_FILE}
        ;;
*)
        whiptail --msgbox "Configuration failed" 12 50 2
        exit
        ;;
esac

whiptail --yesno "Would you like to reboot now?" 20 60 2
if [ $? -eq 0 ]; then
        killall -TERM cgminer
        killall -TERM bfgminer
        sleep 5
        sync
        reboot
fi
exit 0
